# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vimeo_id', models.CharField(default=b'130842805', max_length=500)),
                ('video_thumbnail', models.ImageField(upload_to=b'img/')),
                ('learning_level', models.PositiveSmallIntegerField(default=1)),
                ('unlock_lvl', models.PositiveSmallIntegerField(default=0)),
                ('reward_default', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
    ]
