# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'video_tag', max_length=100)),
                ('start', models.PositiveSmallIntegerField(default=1)),
                ('end', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='vimeo_id',
            field=models.CharField(default=b'208337377', max_length=500),
        ),
        migrations.AddField(
            model_name='videotag',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
    ]
