# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20170615_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=b'video_tag', max_length=100)),
                ('time', models.PositiveSmallIntegerField(default=1)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
        ),
    ]
