# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoquestion',
            old_name='text',
            new_name='question_text',
        ),
    ]
