# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20170615_1021'),
    ]

    operations = [
    ]
