# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20170615_1121'),
    ]

    operations = [
    ]
