# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20170615_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotag',
            name='status',
            field=models.CharField(choices=[(b'SEEN', b'Seen'), (b'UNSEEN', b'Unseen')], max_length=6),
        ),
    ]
