# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20170615_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotag',
            name='status',
            field=models.CharField(choices=[(b'unseen', b'unseen'), (b'seen', b'seen')], max_length=256),
        ),
    ]
